name: Run Java examples

on:
  workflow_dispatch:
  schedule:
    - cron: '35 22 * * *'
  pull_request:
    branches:
      - trunk
    paths:
      - 'examples/java/**'
  push:
    branches:
      - trunk
    paths:
      - 'examples/java/**'

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
        release: [ stable, nightly ]
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Remove driver directories Windows
      if: matrix.os == 'windows'
      run: |
        rm "$env:ChromeWebDriver" -r -v
        rm "$env:EdgeWebDriver" -r -v
        rm "$env:GeckoWebDriver" -r -v
    - name: Remove driver directories Non-Windows
      if: matrix.os != 'windows'
      run: |
        sudo rm -rf $CHROMEWEBDRIVER $EDGEWEBDRIVER $GECKOWEBDRIVER
    - name: Start Xvfb
      if: matrix.os == 'ubuntu'
      run: Xvfb :99 &
    - name: Set up Java
      id: java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Import test cert non-Windows
      if: matrix.os != 'windows'
      run: sudo keytool -import -noprompt -trustcacerts -alias SeleniumHQ -file examples/java/src/test/resources/tls.crt -keystore ${{ steps.java.outputs.path }}/lib/security/cacerts -storepass changeit
    - name: Import test cert Windows
      if: matrix.os == 'windows'
      run: keytool -import -noprompt -trustcacerts -alias SeleniumHQ -file examples/java/src/test/resources/tls.crt -keystore ${{ steps.java.outputs.path }}/lib/security/cacerts -storepass changeit
    - name: Run Tests Stable
      if: matrix.release == 'stable'
      uses: nick-invision/retry@v3.0.0
      with:
        timeout_minutes: 40
        max_attempts: 3
        command: |
          cd examples/java
          mvn -B test -D"jdk.internal.httpclient.disableHostnameVerification=true"
    - name: Run Tests Nightly Linux/macOS
      if: matrix.release == 'nightly' && matrix.os != 'windows'
      uses: nick-invision/retry@v3.0.0
      with:
        timeout_minutes: 40
        max_attempts: 3
        command: |
          pip install yq
          xml_content=$(curl -sf https://oss.sonatype.org/service/local/repositories/snapshots/content/org/seleniumhq/selenium/selenium-java/)
          latest_snapshot=$(echo "$xml_content" | xq '.content.data."content-item"' | jq -r 'sort_by(.lastModified) | last | .text')
          echo "Latest Selenium Snapshot: $latest_snapshot"
          cd examples/java
          mvn -B -U test -D"jdk.internal.httpclient.disableHostnameVerification=true"

    - name: Run Tests Nightly Windows
      if: matrix.release == 'nightly' && matrix.os == 'windows'
      uses: nick-invision/retry@v3.0.0
      with:
        timeout_minutes: 40
        max_attempts: 3
        command: |
          pip install yq          
          $xml_content = Invoke-WebRequest -Uri "https://oss.sonatype.org/service/local/repositories/snapshots/content/org/seleniumhq/selenium/selenium-java/"
          $latest_snapshot = $xml_content.Content | xq '.content.data.\"content-item\"' | jq -r 'sort_by(.lastModified) | last | .text'
          Write-Output "Latest Selenium Snapshot: $latest_snapshot"
          cd examples/java
          mvn -B -U test -D"jdk.internal.httpclient.disableHostnameVerification=true"
